- name: Install ZSH
  apt: name=zsh
  tags:
  - zsh
- name: Change Shell
  shell: chsh -s `which zsh`
  tags:
  - zsh
- name: Install OhMyZSH
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - zsh
- name: Install zsh plugin for autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
  - zsh
- name: Install zsh plugin for autojump
  apt: name=autojump
  tags:
  - zsh
- name: Update ZSHrc
  shell: sed -i 's/(git/(git autojump zsh-autosuggestions/' ~/.zshrc
  tags:
  - zsh
